// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvip7hotA9LMumDRef1lMihPc5mBLk6AM',
    appId: '1:866830330084:web:c00fe81ef5815b455364f1',
    messagingSenderId: '866830330084',
    projectId: 'dalel-a8246',
    authDomain: 'dalel-a8246.firebaseapp.com',
    storageBucket: 'dalel-a8246.firebasestorage.app',
    measurementId: 'G-KVCZD1WXXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMg4fWCu1EPMrWkrERGbjvyGEZb6xnMwo',
    appId: '1:866830330084:android:b7d4c62cfba7876b5364f1',
    messagingSenderId: '866830330084',
    projectId: 'dalel-a8246',
    storageBucket: 'dalel-a8246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARCo7fQ06q7ChTSkzEXIjSTKhBuCQWZKo',
    appId: '1:866830330084:ios:1ae4aa32aa47ac3f5364f1',
    messagingSenderId: '866830330084',
    projectId: 'dalel-a8246',
    storageBucket: 'dalel-a8246.firebasestorage.app',
    iosBundleId: 'com.example.dalelAiCreate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARCo7fQ06q7ChTSkzEXIjSTKhBuCQWZKo',
    appId: '1:866830330084:ios:1ae4aa32aa47ac3f5364f1',
    messagingSenderId: '866830330084',
    projectId: 'dalel-a8246',
    storageBucket: 'dalel-a8246.firebasestorage.app',
    iosBundleId: 'com.example.dalelAiCreate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvip7hotA9LMumDRef1lMihPc5mBLk6AM',
    appId: '1:866830330084:web:22f4dbf5d5b144455364f1',
    messagingSenderId: '866830330084',
    projectId: 'dalel-a8246',
    authDomain: 'dalel-a8246.firebaseapp.com',
    storageBucket: 'dalel-a8246.firebasestorage.app',
    measurementId: 'G-9F0JY1DTFZ',
  );
}
